name:
  enable: true
  value: '&aname'
forgeicon:
  enable: true
  value: 'VANILLA'
protocol:
  enable: true
  value: 2
motd:
  enable: true
  value:
    - '&amotd1'
    - '&bmotd2'
players:
  enable: true
  value:
  - '&cplayer1'
  - '&dplayer2'